// app/utils/tallyXmlTemplates.js

/**
 * Interface for TallyPurchaseOrderData
 * @typedef {Object} TallyPurchaseOrderData
 * @property {string} vouchernumber
 * @property {string} poDate - YYYYMMDD format
 * @property {string} voucherGuid
 * @property {string} voucherKey
 * @property {string} supplierName
 * @property {string} itemName
 * @property {string} itemHSN
 * @property {string} primaryUnit - e.g., 'MT'
 * @property {string} alternativeUnit - e.g., 'Kgs'
 * @property {number} quantity - This quantity should be in the primaryUnit (e.g., 50 MT)
 * @property {number} rate - This rate should be per alternativeUnit (e.g., 9 per Kgs)
 * @property {string} orderDueDate - DD-Mon-YY format
 * @property {string} orderDueDateJD - Julian Date string
 * @property {number} damageAllowed
 * @property {number} cargoPer - Optional, if not provided, defaults to 0
 */

/**
 * Generate Purchase Order Tally XML Object
 * @param {TallyPurchaseOrderData} data 
 * @returns {Object} Tally XML object
 */
export const getPurchaseOrderTallyXmlObject = (data) => {
  const {
    vouchernumber,
    poDate, // YYYYMMDD
    voucherGuid,
    voucherKey,
    supplierName,
    itemName,
    itemHSN,
    primaryUnit,
    alternativeUnit,
    quantity,
    rate,
    orderDueDate, // DD-Mon-YY
    orderDueDateJD, // Julian Date string
    damageAllowed,
    cargoPer,
    podiRate
  } = data;

  const conversionFactor = 1000;
  const qtyInAlternativeUnit = quantity * conversionFactor;
  const actualItemAmount = (quantity * conversionFactor * rate);

  const today = new Date();
  const currentYear = today.getFullYear();
  const currentMonth = (today.getMonth() + 1).toString().padStart(2, '0');
  const currentDay = today.getDate().toString().padStart(2, '0');
  const currentDateFormatted = `${currentYear}${currentMonth}${currentDay}`;

  // Your existing TALLYMESSAGE content.
  // We'll define this inner part and then wrap it in the ENVELOPE.
  const tallyMessageContent = {
    // --- FIX: Correct namespace declaration using '@' prefix ---
    '@xmlns:UDF': 'TallyUDF',    
    VOUCHER: {
      _attr: {
        REMOTEID: `${voucherGuid}-0000008e`,
        VCHKEY: voucherKey,
        VCHTYPE: 'Purchase Order',
        ACTION: 'Create',
        OBJVIEW: 'Invoice Voucher View',
      },
      'BASICBUYERADDRESS.LIST': {
        _attr: { TYPE: 'String' },
        'BASICBUYERADDRESS': [
          'Door.No.2 ( Room A )',
          'First Floor,Dr.Radhakrishnan Salai,',
          '9th Street,Mylapore.',
          'Chennai - 600 004.',
          'Ph: 044 45030377, Mobile 9962611155',
          'E-Mail : ramexpo1993@gmail.com',
        ],
      },
      'OLDAUDITENTRYIDS.LIST': {
        _attr: { TYPE: 'Number' },
        'OLDAUDITENTRYIDS': -1,
      },
      ALTEREDON: currentDateFormatted,
      DATE: poDate,
      VCHSTATUSDATE: poDate,
      GUID: voucherGuid,
      GSTREGISTRATIONTYPE: 'Unregistered/Consumer',
      VATDEALERTYPE: 'Regular',
      STATENAME: 'Tamil Nadu',
      ENTEREDBY: 'admin',
      ALTEREDBY: 'admin',
      COUNTRYOFRESIDENCE: 'India',
      PLACEOFSUPPLY: 'Tamil Nadu',
      TAXUNITNAME: 'Ramasamy Exports Imports Pvt Ltd',
      VOUCHERTYPENAME: 'Purchase Order',
      PARTYNAME: supplierName,
      GSTREGISTRATION: {
        '#text': 'Tamil Nadu Registration', // Corrected
        _attr: { TAXTYPE: 'GST', TAXREGISTRATION: '33AAACR2454C1ZY' }, // Attributes go alongside #text
      },
      CMPGSTIN: '33AAACR2454C1ZY',
      PARTYLEDGERNAME: supplierName,
      VOUCHERNUMBER: vouchernumber,
      BASICBUYERNAME: 'Ramasamy Exports & Imports Pvt.Ltd [22 - 23]',
      CMPGSTREGISTRATIONTYPE: 'Regular',
      REFERENCE: vouchernumber,
      PARTYMAILINGNAME: supplierName,
      CONSIGNEEGSTIN: '33AAACR2454C1ZY',
      CONSIGNEEMAILINGNAME: 'Ramasamy Exports & Imports Pvt.Ltd',
      CONSIGNEEPINCODE: '600107',
      CONSIGNEESTATENAME: 'Tamil Nadu',
      CMPGSTSTATE: 'Tamil Nadu',
      CONSIGNEECOUNTRYNAME: 'India',
      BASICBASEPARTYNAME: supplierName,
      NUMBERINGSTYLE: 'Manual',
      CSTFORMISSUETYPE: 'Default',
      CSTFORMRECVTYPE: 'Default',
      CONSIGNEECSTNUMBER: '78993',
      TRADERCONSVATTINNO: '33490080720',
      FBTPAYMENTTYPE: 'Default',
      PERSISTEDVIEW: 'Invoice Voucher View',
      TYPEOFEXCISEVOUCHER: 'Non-Excise',
      VCHSTATUSTAXADJUSTMENT: 'Default',
      VCHSTATUSVOUCHERTYPE: 'Purchase Order',
      VCHSTATUSTAXUNIT: 'Tamil Nadu Registration',
      VCHGSTCLASS: 'Not Applicable',
      CONSIGNEEPINNUMBER: 'AAACR2454C',
      VCHENTRYMODE: 'Item Invoice',
      VOUCHERTYPEORIGNAME: 'Purchase Order',
      DIFFACTUALQTY: 'No',
      ISMSTFROMSYNC: 'No',
      ISDELETED: 'No',
      ISSECURITYONWHENENTERED: 'No',
      ASORIGINAL: 'No',
      AUDITED: 'No',
      ISCOMMONPARTY: 'No',
      FORJOBCOSTING: 'No',
      ISOPTIONAL: 'No',
      EFFECTIVEDATE: poDate,
      USEFOREXCISE: 'No',
      ISFORJOBWORKIN: 'No',
      ALLOWCONSUMPTION: 'No',
      USEFORINTEREST: 'No',
      USEFORGAINLOSS: 'No',
      USEFORGODOWNTRANSFER: 'No',
      USEFORCOMPOUND: 'No',
      USEFORSERVICETAX: 'No',
      ISREVERSECHARGEAPPLICABLE: 'No',
      ISSYSTEM: 'No',
      ISFETCHEDONLY: 'No',
      ISGSTOVERRIDDEN: 'No',
      ISCANCELLED: 'No',
      ISONHOLD: 'No',
      ISSUMMARY: 'No',
      ISECOMMERCESUPPLY: 'No',
      ISBOENOTAPPLICABLE: 'No',
      ISGSTSECSEVENAPPLICABLE: 'No',
      IGNOREEINVVALIDATION: 'No',
      CMPGSTISOTHTERRITORYASSESSEE: 'No',
      PARTYGSTISOTHTERRITORYASSESSEE: 'No',
      IRNJSONEXPORTED: 'No',
      IRNCANCELLED: 'No',
      IGNOREGSTCONFLICTINMIG: 'No',
      ISOPBALTRANSACTION: 'No',
      IGNOREGSTFORMATVALIDATION: 'No',
      ISELIGIBLEFORITC: 'Yes',
      IGNOREGSTOPTIONALUNCERTAIN: 'No',
      UPDATESUMMARYVALUES: 'No',
      ISEWAYBILLAPPLICABLE: 'No',
      ISDELETEDRETAINED: 'No',
      ISNULL: 'No',
      ISEXCISEVOUCHER: 'No',
      EXCISETAXOVERRIDE: 'No',
      USEFORTAXUNITTRANSFER: 'No',
      ISEXER1NOPOVERWRITE: 'No',
      ISEXF2NOPOVERWRITE: 'No',
      ISEXER3NOPOVERWRITE: 'No',
      IGNOREPOSVALIDATION: 'No',
      EXCISEOPENING: 'No',
      USEFORFINALPRODUCTION: 'No',
      ISTDSOVERRIDDEN: 'No',
      ISTCSOVERRIDDEN: 'No',
      ISTDSTCSCASHVCH: 'No',
      INCLUDEADVPYMTVCH: 'No',
      ISSUBWORKSCONTRACT: 'No',
      ISVATOVERRIDDEN: 'No',
      IGNOREORIGVCHDATE: 'No',
      ISVATPAIDATCUSTOMS: 'Yes',
      ISDECLAREDTOCUSTOMS: 'No',
      VATADVANCEPAYMENT: 'No',
      VATADVPAY: 'No',
      ISCSTDELCAREDGOODSSALES: 'No',
      ISVATRESTAXINV: 'No',
      ISSERVICETAXOVERRIDDEN: 'No',
      ISISDVOUCHER: 'No',
      ISEXCISEOVERRIDDEN: 'No',
      ISEXCISESUPPLYVCH: 'No',
      GSTNOTEXPORTED: 'No',
      IGNOREGSTINVALIDATION: 'No',
      ISGSTREFUND: 'No',
      OVRDNEWAYBILLAPPLICABILITY: 'No',
      ISVATPRINCIPALACCOUNT: 'No',
      VCHSTATUSISVCHNUMUSED: 'No',
      VCHGSTSTATUSISINCLUDED: 'No',
      VCHGSTSTATUSISUNCERTAIN: 'No',
      VCHGSTSTATUSISEXCLUDED: 'No',
      VCHGSTSTATUSISAPPLICABLE: 'No',
      VCHGSTSTATUSISGSTR2BRECONCILED: 'No',
      VCHGSTSTATUSISGSTR2BONLYINPORTAL: 'No',
      VCHGSTSTATUSISGSTR2BONLYINBOOKS: 'No',
      VCHGSTSTATUSISGSTR2BMISMATCH: 'No',
      VCHGSTSTATUSISGSTR2BINDIFFPERIOD: 'No',
      VCHGSTSTATUSISRETEFFDATEOVERRDN: 'No',
      VCHGSTSTATUSISOVERRDN: 'No',
      VCHGSTSTATUSISSTATINDIFFDATE: 'No',
      VCHGSTSTATUSISRETINDIFFDATE: 'No',
      VCHGSTSTATUSMAINSECTIONEXCLUDED: 'No',
      VCHGSTSTATUSISBRANCHTRANSFEROUT: 'No',
      VCHGSTSTATUSISSYSTEMSUMMARY: 'No',
      VCHSTATUSISUNREGISTEREDRCM: 'No',
      VCHSTATUSISOPTIONAL: 'No',
      VCHSTATUSISCANCELLED: 'No',
      VCHSTATUSISDELETED: 'No',
      VCHSTATUSISOPENINGBALANCE: 'No',
      VCHSTATUSISFETCHEDONLY: 'No',
      VCHGSTSTATUSISOPTIONALUNCERTAIN: 'No',
      VCHSTATUSISREACCEPTFORHSNDONE: 'No',
      VCHSTATUSISREACCEPHSNSIXONEDONE: 'No',
      PAYMENTLINKHASMULTIREF: 'No',
      ISSHIPPINGWITHINSTATE: 'No',
      ISOVERSEASTOURISTTRANS: 'No',
      ISDESIGNATEDZONEPARTY: 'No',
      HASCASHFLOW: 'No',
      ISPOSTDATED: 'No',
      USETRACKINGNUMBER: 'No',
      ISINVOICE: 'No',
      MFGJOURNAL: 'No',
      HASDISCOUNTS: 'No',
      ASPAYSLIP: 'No',
      ISCOSTCENTRE: 'No',
      ISSTXNONREALIZEDVCH: 'No',
      ISEXCISEMANUFACTURERON: 'No',
      ISBLANKCHEQUE: 'No',
      ISVOID: 'No',
      ORDERLINESTATUS: 'No',
      VATISAGNSTCANCSALES: 'No',
      VATISPURCEXEMPTED: 'No',
      VATISASSESABLECALCVCH: 'No',
      ISVATDUTYPAID: 'Yes',
      ISDELIVERYSAMEASCONSIGNEE: 'No',
      ISDISPATCHSAMEASCONSIGNOR: 'No',
      ISDELETEDVCHRETAINED: 'No',
      VCHONLYADDLINFOUPDATED: 'No',
      CHANGEVCHMODE: 'No',
      RESETIRNQRCODE: 'No',

      ALTERID: ' 23921',
      MASTERID: ' 142',
      VOUCHERKEY: voucherKey,
      VOUCHERRETAINKEY: '29',
      VOUCHERNUMBERSERIES: 'Default',
      'EWAYBILLDETAILS.LIST': {},
      'EXCLUDEDTAXATIONS.LIST': {},
      'OLDAUDITENTRIES.LIST': {},
      'ACCOUNTAUDITENTRIES.LIST': {},
      'AUDITENTRIES.LIST': {},
      'DUTYHEADDETAILS.LIST': {},
      'GSTADVADJDETAILS.LIST': {},

      'ALLINVENTORYENTRIES.LIST': {
        STOCKITEMNAME: itemName,
        GSTOVRDNINELIGIBLEITC: 'Applicable',
        GSTOVRDNISREVCHARGEAPPL: 'Not Applicable',
        GSTOVRDNTAXABILITY: 'Exempt',
        GSTSOURCETYPE: 'Ledger',
        GSTLEDGERSOURCE: 'Onion Purchase',
        HSNSOURCETYPE: 'Ledger',
        HSNLEDGERSOURCE: 'Onion Purchase',
        GSTOVRDNSTOREDNATURE: 'Interstate Purchase - Exempt',
        GSTOVRDNTYPEOFSUPPLY: 'Goods',
        GSTRATEINFERAPPLICABILITY: 'As per Masters/Company',
        GSTHSNNAME: itemHSN,
        GSTHSNINFERAPPLICABILITY: 'As per Masters/Company',
        ISDEEMEDPOSITIVE: 'Yes',
        ISGSTASSESSABLEVALUEOVERRIDDEN: 'No',
        STRDISGSTAPPLICABLE: 'No',
        CONTENTNEGISPOS: 'No',
        ISLASTDEEMEDPOSITIVE: 'Yes',
        ISAUTONEGATE: 'No',
        ISCUSTOMSCLEARANCE: 'No',
        ISTRACKCOMPONENT: 'No',
        ISTRACKPRODUCTION: 'No',
        ISPRIMARYITEM: 'No',
        ISSCRAP: 'No',
        RATE: `${rate.toFixed(2)}/${alternativeUnit}`,
        AMOUNT: (-actualItemAmount).toFixed(2),
        ACTUALQTY: `${quantity.toFixed(3)} ${primaryUnit} = ${qtyInAlternativeUnit.toFixed(3)} ${alternativeUnit}`,
        BILLEDQTY: `${quantity.toFixed(3)} ${primaryUnit} = ${qtyInAlternativeUnit.toFixed(3)} ${alternativeUnit}`,
        'BATCHALLOCATIONS.LIST': {
          GODOWNNAME: 'Main Location',
          BATCHNAME: 'Primary Batch',
          INDENTNO: 'Not Applicable',
          ORDERNO: vouchernumber,
          TRACKINGNUMBER: 'Not Applicable',
          DYNAMICCSTISCLEARED: 'No',
          AMOUNT: (-actualItemAmount).toFixed(2),
          ACTUALQTY: `${quantity.toFixed(3)} ${primaryUnit} = ${qtyInAlternativeUnit.toFixed(3)} ${alternativeUnit}`,
          BILLEDQTY: `${quantity.toFixed(3)} ${primaryUnit} = ${qtyInAlternativeUnit.toFixed(3)} ${alternativeUnit}`,
          // --- FIX 2: ORDERDUEDATE Structure ---
          //ORDERDUEDATE:`JD="45861" P="24-Jul-25">24-Jul-25`,
          ORDERDUEDATE: "1 Day",
          'ADDITIONALDETAILS.LIST': {},
          'VOUCHERCOMPONENTLIST.LIST': {},
        },
        'ACCOUNTINGALLOCATIONS.LIST': {
          'OLDAUDITENTRYIDS.LIST': {
            _attr: { TYPE: 'Number' },
            'OLDAUDITENTRYIDS': -1
          },
          LEDGERNAME: 'Onion Purchase',
          GSTCLASS: 'Not Applicable',
          ISDEEMEDPOSITIVE: 'Yes',
          LEDGERFROMITEM: 'No',
          REMOVEZEROENTRIES: 'No',
          ISPARTYLEDGER: 'No',
          GSTOVERRIDDEN: 'No',
          ISGSTASSESSABLEVALUEOVERRIDDEN: 'No',
          STRDISGSTAPPLICABLE: 'No',
          STRDGSTISPARTYLEDGER: 'No',
          STRDGSTISDUTYLEDGER: 'No',
          CONTENTNEGISPOS: 'No',
          ISLASTDEEMEDPOSITIVE: 'Yes',
          ISCAPVATTAXALTERED: 'No',
          ISCAPVATNOTCLAIMED: 'No',
          AMOUNT: (-actualItemAmount).toFixed(2),
          'SERVICETAXDETAILS.LIST': {},
          'BANKALLOCATIONS.LIST': {},
          'BILLALLOCATIONS.LIST': {},
          'INTERESTCOLLECTION.LIST': {},
          'OLDAUDITENTRIES.LIST': {},
          'ACCOUNTAUDITENTRIES.LIST': {},
          'AUDITENTRIES.LIST': {},
          'INPUTCRALLOCS.LIST': {},
          'DUTYHEADDETAILS.LIST': {},
          'EXCISEDUTYHEADDETAILS.LIST': {},
          'RATEDETAILS.LIST': {},
          'SUMMARYALLOCS.LIST': {},
          'CENVATDUTYALLOCATIONS.LIST': {},
          'STPYMTDETAILS.LIST': {},
          'EXCISEPAYMENTALLOCATIONS.LIST': {},
          'TAXBILLALLOCATIONS.LIST': {},
          'TAXOBJECTALLOCATIONS.LIST': {},
          'TDSEXPENSEALLOCATIONS.LIST': {},
          'VATSTATUTORYDETAILS.LIST': {},
          'COSTTRACKALLOCATIONS.LIST': {},
          'REFVOUCHERDETAILS.LIST': {},
          'INVOICEWISEDETAILS.LIST': {},
          'VATITCDETAILS.LIST': {},
          'ADVANCETAXDETAILS.LIST': {},
          'TAXTYPEALLOCATIONS.LIST': {},
        },
        'DUTYHEADDETAILS.LIST': {},
        'RATEDETAILS.LIST': [
          { GSTRATEDUTYHEAD: 'CGST', GSTRATEVALUATIONTYPE: 'Based on Value' },
          { GSTRATEDUTYHEAD: 'SGST/UTGST', GSTRATEVALUATIONTYPE: 'Based on Value' },
          { GSTRATEDUTYHEAD: 'IGST', GSTRATEVALUATIONTYPE: 'Based on Value' },
          { GSTRATEDUTYHEAD: 'Cess', GSTRATEVALUATIONTYPE: 'Not Applicable' },
          { GSTRATEDUTYHEAD: 'State Cess', GSTRATEVALUATIONTYPE: 'Based on Value' },
        ],
        'SUPPLEMENTARYDUTYHEADDETAILS.LIST': {},
        'TAXOBJECTALLOCATIONS.LIST': {},
        'REFVOUCHERDETAILS.LIST': {},
        'EXCISEALLOCATIONS.LIST': {},
        'EXPENSEALLOCATIONS.LIST': {},
      },

      'CONTRITRANS.LIST': {},
      'EWAYBILLERRORLIST.LIST': {},
      'IRNERRORLIST.LIST': {},
      'HARYANAVAT.LIST': {},
      'SUPPLEMENTARYDUTYHEADDETAILS.LIST': {},
      'INVOICEDELNOTES.LIST': {},
      'INVOICEORDERLIST.LIST': {},
      'INVOICEINDENTLIST.LIST': {},
      'ATTENDANCEENTRIES.LIST': {},
      'ORIGINVOICEDETAILS.LIST': {},
      'INVOICEEXPORTLIST.LIST': {},
      'LEDGERENTRIES.LIST': [
        {
          'OLDAUDITENTRYIDS.LIST': {
            _attr: { TYPE: 'Number' },
            'OLDAUDITENTRYIDS': -1
          },
          LEDGERNAME: supplierName,
          GSTCLASS: 'Not Applicable',
          ISDEEMEDPOSITIVE: 'No',
          LEDGERFROMITEM: 'No',
          REMOVEZEROENTRIES: 'No',
          ISPARTYLEDGER: 'Yes',
          GSTOVERRIDDEN: 'No',
          ISGSTASSESSABLEVALUEOVERRIDDEN: 'No',
          STRDISGSTAPPLICABLE: 'No',
          STRDGSTISPARTYLEDGER: 'No',
          STRDGSTISDUTYLEDGER: 'No',
          CONTENTNEGISPOS: 'No',
          ISLASTDEEMEDPOSITIVE: 'No',
          ISCAPVATTAXALTERED: 'No',
          ISCAPVATNOTCLAIMED: 'No',
          AMOUNT: actualItemAmount.toFixed(2),
          'SERVICETAXDETAILS.LIST': {},
          'BANKALLOCATIONS.LIST': {},
          'BILLALLOCATIONS.LIST': {},
          'INTERESTCOLLECTION.LIST': {},
          'OLDAUDITENTRIES.LIST': {},
          'ACCOUNTAUDITENTRIES.LIST': {},
          'AUDITENTRIES.LIST': {},
          'INPUTCRALLOCS.LIST': {},
          'DUTYHEADDETAILS.LIST': {},
          'EXCISEDUTYHEADDETAILS.LIST': {},
          'RATEDETAILS.LIST': {},
          'SUMMARYALLOCS.LIST': {},
          'CENVATDUTYALLOCATIONS.LIST': {},
          'STPYMTDETAILS.LIST': {},
          'EXCISEPAYMENTALLOCATIONS.LIST': {},
          'TAXBILLALLOCATIONS.LIST': {},
          'TAXOBJECTALLOCATIONS.LIST': {},
          'TDSEXPENSEALLOCATIONS.LIST': {},
          'VATSTATUTORYDETAILS.LIST': {},
          'COSTTRACKALLOCATIONS.LIST': {},
          'REFVOUCHERDETAILS.LIST': {},
          'INVOICEWISEDETAILS.LIST': {},
          'VATITCDETAILS.LIST': {},
          'ADVANCETAXDETAILS.LIST': {},
          'TAXTYPEALLOCATIONS.LIST': {},
        },
      ],
      'GST.LIST': {},
      'STKJRNLADDLCOSTDETAILS.LIST': {},
      'PAYROLLMODEOFPAYMENT.LIST': {},
      'ATTDRECORDS.LIST': {},
      'GSTEWAYCONSIGNORADDRESS.LIST': {},
      'GSTEWAYCONSIGNEEADDRESS.LIST': {},
      'TEMPGSTRATEDETAILS.LIST': {},
      'TEMPGSTADVADJUSTED.LIST': {},
      'GSTBUYERADDRESS.LIST': {},
      'GSTCONSIGNEEADDRESS.LIST': {},
      // --- FIX 3: UDF:RAM_DAMAGE Structure ---
      'UDF:RAM_DAMAGE.LIST': {
        _attr: { DESC: '`ram_damage`', ISLIST: 'YES', TYPE: 'Number', INDEX: '11035' },
        'UDF:RAM_DAMAGE': {
          '#text': damageAllowed?.toString() || '0',
          _attr: { DESC: '`ram_damage`' },
        },
      },
      // --- FIX 4: UDF:RAM_CARGO Structure ---
      'UDF:RAM_CARGO.LIST': {
        _attr: { DESC: '`ram_cargo`', ISLIST: 'YES', TYPE: 'Number', INDEX: '11036' },
        'UDF:RAM_CARGO': {
          '#text': cargoPer?.toString() || '0',
          _attr: { DESC: '`ram_cargo`' },
        },
      },
    },
      // --- FIX 4: UDF:RAM_CARGO Structure ---
      'UDF:ram_po_podi_rate.LIST': {
        _attr: { DESC: '`ram_po_podi_rate`', ISLIST: 'YES', TYPE: 'Number', INDEX: '11048' },
        'UDF:ram_po_podi_rate': {
          '#text': podiRate?.toString() || '0',
          _attr: { DESC: '`ram_po_podi_rate`' },
        },
      },
  };

  // --- FIX 1: Removed the duplicate ENVELOPE tag ---
  return {
    ENVELOPE: {
      HEADER: {
        VERSION: '1',
        TALLYREQUEST: 'Import Data',
        TYPE: 'Data',
        ID: 'Vouchers',
      },
      BODY: {
        DESC:{
          STATICVARIABLES:{
             SVCURRENTCOMPANY:`Ramasamy Exports &amp; Imports Pvt.Ltd [22 - 23]`
          }
        },
        IMPORTDATA: {
          REQUESTDESC: {
            REPORTNAME: 'Vouchers',
          },
          REQUESTDATA: {
            TALLYMESSAGE: tallyMessageContent,
          },
        },
      },
    },
  };
}